import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding Bridge to Agentia Luxury Fashion & Apparel Database...');

  // 1. Clean existing data cleanly
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.wishlistItem.deleteMany();
  await prisma.wishlist.deleteMany();
  await prisma.review.deleteMany();
  await prisma.address.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.coupon.deleteMany();
  await prisma.user.deleteMany();

  // 2. Create Users
  const salt = await bcrypt.genSalt(10);
  const passwordHash = await bcrypt.hash('password123', salt);

  const demoUser = await prisma.user.create({
    data: {
      email: 'demo@agentbridge.io',
      name: 'Alex Rivera',
      passwordHash,
      role: 'CUSTOMER',
      addresses: {
        create: [
          {
            fullName: 'Alex Rivera',
            street: '742 Evergreen Terrace',
            city: 'Springfield',
            state: 'OR',
            zipCode: '97477',
            country: 'United States',
            phone: '+1 (555) 234-5678',
            isDefault: true,
          },
          {
            fullName: 'Alex Rivera (Studio)',
            street: '450 Fashion Avenue, Suite 12',
            city: 'New York',
            state: 'NY',
            zipCode: '10018',
            country: 'United States',
            phone: '+1 (555) 987-6543',
            isDefault: false,
          },
        ],
      },
      cart: { create: {} },
      wishlist: { create: {} },
    },
  });

  const sarahUser = await prisma.user.create({
    data: {
      email: 'sarah.j@example.com',
      name: 'Sarah Jenkins',
      passwordHash,
      role: 'CUSTOMER',
      cart: { create: {} },
      wishlist: { create: {} },
    },
  });

  // 3. Create Fashion Categories
  const catWomensTops = await prisma.category.create({
    data: {
      name: "Women's Tops & Blouses",
      slug: 'womens-tops',
      description: 'Elegant silk blouses, tailored peplums, wrap tops, and lightweight summer camisoles in vibrant hues.',
      image: 'https://images.unsplash.com/photo-1534126511673-b6899657816a?w=800&q=80',
    },
  });

  const catMensTshirts = await prisma.category.create({
    data: {
      name: "Men's Luxury T-Shirts",
      slug: 'mens-tshirts',
      description: 'Essential crewneck and v-neck tees crafted from Supima, mercerized cotton, and heavyweight organic fabrics.',
      image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
    },
  });

  const catWomensJeans = await prisma.category.create({
    data: {
      name: "Women's Premium Denim",
      slug: 'womens-jeans',
      description: 'High-rise straight leg, ankle crop, and tailored wide-leg trousers tailored with premium comfort stretch.',
      image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
    },
  });

  const catMensJeans = await prisma.category.create({
    data: {
      name: "Men's Tailored Denim",
      slug: 'mens-jeans',
      description: 'Raw selvedge, vintage stonewash, slim tapered, and classic straight leg denim made for durability and comfort.',
      image: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&q=80',
    },
  });

  // 4. Products Array - EXACT SPECIFICATION:
  // - 10 Red Female Tops
  // - 12 Blue Female Tops
  // - 9 Green Female Tops
  // - 5 Black Male T-Shirts
  // - 8 White Male T-Shirts
  // - 10 Blue Male T-Shirts
  // - 3 Female Jeans
  // - 5 Male Jeans
  // TOTAL: 62 products

  const productsData: any[] = [
    // =========================================================================
    // FEMALE TOPS — 10 RED TOPS
    // =========================================================================
    {
      name: 'Crimson Silk Charmeuse Blouse',
      slug: 'crimson-silk-charmeuse-blouse',
      description: 'Crafted from pure Mulberry silk charmeuse with a luminous sheen, delicate French seams, and a tailored collar.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 185.00,
      discountPercent: 10,
      rating: 4.9,
      reviewCount: 42,
      stock: 18,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=800&q=80',
        'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#DC2626',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: '100% Mulberry Silk',
        Fit: 'Tailored Relaxed Fit',
        'Care Instructions': 'Dry clean only or delicate hand wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'silk', 'blouse', 'formal', 'evening']),
      isFeatured: true,
      isPromoted: true,
    },
    {
      name: 'Ruby Peplum Evening Top',
      slug: 'ruby-peplum-evening-top',
      description: 'Structured peplum silhouette in rich ruby red with an architectural sweetheart neckline and back gold zip.',
      categoryId: catWomensTops.id,
      brand: 'Maison Luxe',
      price: 145.00,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 29,
      stock: 14,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1534126511673-b6899657816a?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#B91C1C',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: 'Double-Knit Ponte (68% Rayon, 28% Nylon, 4% Spandex)',
        Fit: 'Fitted Peplum',
        'Care Instructions': 'Machine wash cold on gentle cycle',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'peplum', 'evening', 'party']),
    },
    {
      name: 'Scarlet Ribbed Knit Camisole',
      slug: 'scarlet-ribbed-knit-camisole',
      description: 'A versatile essential rendered in fine scarlet rib-knit with slim straps and a flattering scoop neckline.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 65.00,
      discountPercent: 15,
      rating: 4.7,
      reviewCount: 38,
      stock: 25,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#EF4444',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: 'Organic Cotton & Silk Blend',
        Fit: 'Slim Ribbed Fit',
        'Care Instructions': 'Machine wash cold delicate',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'camisole', 'knit', 'casual']),
    },
    {
      name: 'Burgundy Lace-Trim Crepe Top',
      slug: 'burgundy-lace-trim-crepe-top',
      description: 'Deep burgundy crepe top with eyelash Chantilly lace embroidery along the neckline and cuffs.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 130.00,
      discountPercent: 0,
      rating: 4.6,
      reviewCount: 22,
      stock: 12,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#881337',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'S, M, L, XL',
        Material: 'Matte Georgette Crepe & French Lace',
        Fit: 'Classic Regular Fit',
        'Care Instructions': 'Hand wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'burgundy', 'lace', 'formal']),
    },
    {
      name: 'Cherry Red Tailored Wrap Blouse',
      slug: 'cherry-red-tailored-wrap-blouse',
      description: 'Surplice wrap front that cinches at the natural waist with an adjustable sash tie in vibrant cherry red.',
      categoryId: catWomensTops.id,
      brand: 'Maison Luxe',
      price: 115.00,
      discountPercent: 20,
      rating: 4.9,
      reviewCount: 51,
      stock: 20,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1534126511673-b6899657816a?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#DC2626',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: 'Tencel Lyocell Satin',
        Fit: 'Adjustable Wrap Fit',
        'Care Instructions': 'Machine wash cold, line dry',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'wrap', 'blouse', 'workwear']),
      isFeatured: true,
    },
    {
      name: 'Garnet Boatneck Long Sleeve Top',
      slug: 'garnet-boatneck-long-sleeve-top',
      description: 'Sophisticated boatneck long-sleeve silhouette in deep garnet micro-modal with ribbed cuffs.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 85.00,
      discountPercent: 0,
      rating: 4.5,
      reviewCount: 19,
      stock: 16,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#991B1B',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: '95% Micro-Modal, 5% Elastane',
        Fit: 'Fitted Bodycon',
        'Care Instructions': 'Machine wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'boatneck', 'long-sleeve', 'layering']),
    },
    {
      name: 'Rouge Ruffle Chiffon Blouse',
      slug: 'rouge-ruffle-chiffon-blouse',
      description: 'Airy semi-sheer chiffon with cascading romantic ruffles framing the placket in French rouge red.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 125.00,
      discountPercent: 10,
      rating: 4.7,
      reviewCount: 31,
      stock: 15,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#B91C1C',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'S, M, L',
        Material: '100% Recycled Chiffon',
        Fit: 'Flowy Relaxed Fit',
        'Care Instructions': 'Hand wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'ruffle', 'chiffon', 'romantic']),
    },
    {
      name: 'Wine Satin Halter Top',
      slug: 'wine-satin-halter-top',
      description: 'Open-back halter top in liquid wine satin with a draped cowl front and delicate neck button closure.',
      categoryId: catWomensTops.id,
      brand: 'Maison Luxe',
      price: 95.00,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 26,
      stock: 11,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1534126511673-b6899657816a?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#7F1D1D',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: 'Silky Poly Satin Blend',
        Fit: 'Draped Halter',
        'Care Instructions': 'Dry clean or gentle hand wash',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'halter', 'satin', 'cocktail']),
    },
    {
      name: 'Brick Red Linen Button-Down Shirt',
      slug: 'brick-red-linen-button-down-shirt',
      description: 'Relaxed menswear-inspired button-down in pre-washed European linen with mother-of-pearl buttons.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 110.00,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 34,
      stock: 22,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#9A3412',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: '100% French Flax Linen',
        Fit: 'Relaxed Oversized Fit',
        'Care Instructions': 'Machine wash cold, line dry',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'linen', 'button-down', 'casual']),
    },
    {
      name: 'Coral Red Pleated V-Neck Top',
      slug: 'coral-red-pleated-v-neck-top',
      description: 'Micro-pleated accordion texture in warm coral red with bracelet sleeves and a delicate split V-neck.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 105.00,
      discountPercent: 15,
      rating: 4.6,
      reviewCount: 18,
      stock: 17,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Red',
        HexColor: '#E11D48',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'S, M, L, XL',
        Material: 'Pleated Poly Georgette',
        Fit: 'Easy Straight Fit',
        'Care Instructions': 'Machine wash gentle inside laundry bag',
      }),
      tags: JSON.stringify(['women', 'top', 'red', 'coral', 'pleated', 'v-neck']),
    },

    // =========================================================================
    // FEMALE TOPS — 12 BLUE TOPS
    // =========================================================================
    {
      name: 'Royal Blue Silk Button-Down Blouse',
      slug: 'royal-blue-silk-button-down-blouse',
      description: 'Striking royal blue silk blouse with hidden placket, French cuffs, and an impeccably tailored silhouette.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 195.00,
      discountPercent: 10,
      rating: 4.9,
      reviewCount: 47,
      stock: 19,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#1D4ED8',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: '100% Crepe de Chine Silk',
        Fit: 'Classic Tailored Fit',
        'Care Instructions': 'Dry clean only',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'silk', 'blouse', 'luxury', 'formal']),
      isFeatured: true,
      isPromoted: true,
    },
    {
      name: 'Midnight Navy Cashmere Blend Top',
      slug: 'midnight-navy-cashmere-blend-top',
      description: 'Luxuriously soft crewneck knit in deep midnight navy, combining lightweight warmth with timeless elegance.',
      categoryId: catWomensTops.id,
      brand: 'Maison Luxe',
      price: 210.00,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 39,
      stock: 14,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1551803091-e20673f15770?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#1E3A8A',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'S, M, L, XL',
        Material: '70% Mongolian Cashmere, 30% Silk',
        Fit: 'Slim Tailored Fit',
        'Care Instructions': 'Hand wash cold or dry clean',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'navy', 'cashmere', 'knit']),
    },
    {
      name: 'Sky Blue Poplin Structured Shirt',
      slug: 'sky-blue-poplin-structured-shirt',
      description: 'Crisp organic cotton poplin in refreshing sky blue with architectural drop shoulders and curved hemline.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 95.00,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 32,
      stock: 24,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#38BDF8',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: '100% Organic Crisp Cotton Poplin',
        Fit: 'Structured Relaxed Fit',
        'Care Instructions': 'Machine wash warm, iron while damp',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'poplin', 'shirt', 'workwear']),
    },
    {
      name: 'Azure Tiered Flutter Sleeve Top',
      slug: 'azure-tiered-flutter-sleeve-top',
      description: 'Breezy georgette top featuring double flutter sleeves and subtle keyhole neck in luminous azure blue.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 88.00,
      discountPercent: 15,
      rating: 4.6,
      reviewCount: 20,
      stock: 16,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#0284C7',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: 'Polyester Chiffon Crepe',
        Fit: 'A-Line Flowy Fit',
        'Care Instructions': 'Machine wash delicate',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'flutter', 'summer', 'casual']),
    },
    {
      name: 'Sapphire Satin Cowl Neck Top',
      slug: 'sapphire-satin-cowl-neck-top',
      description: 'Liquid sapphire satin drape with an alluring cowl neckline and bias-cut body that hugs natural curves.',
      categoryId: catWomensTops.id,
      brand: 'Maison Luxe',
      price: 120.00,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 35,
      stock: 13,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1551803091-e20673f15770?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#1E40AF',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: 'Heavy Silk Satin',
        Fit: 'Bias Cut Fluid Fit',
        'Care Instructions': 'Hand wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'sapphire', 'cowl-neck', 'cocktail']),
    },
    {
      name: 'Powder Blue Ribbed Scoop Neck Top',
      slug: 'powder-blue-ribbed-scoop-neck-top',
      description: 'Soft pastel powder blue knit in a fine rib texture, featuring a flattering scoop neck and cap sleeves.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 70.00,
      discountPercent: 0,
      rating: 4.5,
      reviewCount: 23,
      stock: 21,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#93C5FD',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: 'Modal Rib Knit Blend',
        Fit: 'Body-Hugging Ribbed Fit',
        'Care Instructions': 'Machine wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'pastel', 'scoop-neck', 'essential']),
    },
    {
      name: 'Cobalt Blue Wrap Peplum Blouse',
      slug: 'cobalt-blue-wrap-peplum-blouse',
      description: 'Bold cobalt blue wrap blouse with structured waist tucks and a flared peplum hem that flatters every silhouette.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 135.00,
      discountPercent: 10,
      rating: 4.8,
      reviewCount: 41,
      stock: 15,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#2563EB',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'S, M, L, XL',
        Material: 'Fine Cotton Twill Blend',
        Fit: 'Tailored Wrap Fit',
        'Care Instructions': 'Dry clean or machine wash cold gentle',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'cobalt', 'wrap', 'peplum']),
    },
    {
      name: 'Slate Blue Linen Relaxed Top',
      slug: 'slate-blue-linen-relaxed-top',
      description: 'Subdued slate blue breathable linen with dolman sleeves, side hem slits, and a clean minimalist aesthetic.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 105.00,
      discountPercent: 0,
      rating: 4.6,
      reviewCount: 27,
      stock: 18,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#64748B',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: '100% Washed European Linen',
        Fit: 'Relaxed Boxy Fit',
        'Care Instructions': 'Machine wash cold, air dry',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'slate', 'linen', 'sustainable']),
    },
    {
      name: 'Indigo Smocked Bodice Blouse',
      slug: 'indigo-smocked-bodice-blouse',
      description: 'Artisanal smocked bodice with squared neckline and puffed elbow-length sleeves in rich indigo blue.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 115.00,
      discountPercent: 12,
      rating: 4.7,
      reviewCount: 30,
      stock: 17,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#312E81',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: '100% Breathable Cotton Voile',
        Fit: 'Fitted Smocked Bodice, Flowy Hem',
        'Care Instructions': 'Hand wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'indigo', 'smocked', 'cottagecore']),
    },
    {
      name: 'Periwinkle Cap Sleeve Fitted Top',
      slug: 'periwinkle-cap-sleeve-fitted-top',
      description: 'Delicate periwinkle blue knit top with delicate ribbing and feminine cap sleeves for effortless layering.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 68.00,
      discountPercent: 0,
      rating: 4.5,
      reviewCount: 16,
      stock: 22,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1551803091-e20673f15770?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#818CF8',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: 'Silk-Cotton Rib Knit',
        Fit: 'Fitted Silhouette',
        'Care Instructions': 'Machine wash cold gentle',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'periwinkle', 'cap-sleeve', 'basic']),
    },
    {
      name: 'Electric Blue Cutout Shoulder Top',
      slug: 'electric-blue-cutout-shoulder-top',
      description: 'Modern statement top in vibrant electric blue jersey featuring an asymmetrical one-shoulder cutout.',
      categoryId: catWomensTops.id,
      brand: 'Maison Luxe',
      price: 90.00,
      discountPercent: 20,
      rating: 4.7,
      reviewCount: 28,
      stock: 14,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#0EA5E9',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'S, M, L',
        Material: 'Heavy Stretch Jersey',
        Fit: 'Asymmetrical Body-Sculpting',
        'Care Instructions': 'Machine wash cold inside out',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'cutout', 'statement', 'night-out']),
    },
    {
      name: 'Ocean Blue Pintuck Cotton Blouse',
      slug: 'ocean-blue-pintuck-cotton-blouse',
      description: 'Intricate pintuck pleating along the chest with mandarin collar in light-filtering ocean blue lawn cotton.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 110.00,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 33,
      stock: 19,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#0369A1',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: '100% Superfine Cotton Lawn',
        Fit: 'Relaxed Straight Fit',
        'Care Instructions': 'Machine wash cold, hang dry',
      }),
      tags: JSON.stringify(['women', 'top', 'blue', 'pintuck', 'cotton', 'classic']),
    },

    // =========================================================================
    // FEMALE TOPS — 9 GREEN TOPS
    // =========================================================================
    {
      name: 'Emerald Green Silk Camisole',
      slug: 'emerald-green-silk-camisole',
      description: 'Lustrous emerald silk with a gently draped V-neck and adjustable gold-hardware spaghetti straps.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 120.00,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 44,
      stock: 16,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Green',
        HexColor: '#059669',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: '100% Pure Mulberry Silk',
        Fit: 'Flowy Bias Cut',
        'Care Instructions': 'Hand wash cold or dry clean',
      }),
      tags: JSON.stringify(['women', 'top', 'green', 'emerald', 'silk', 'camisole']),
      isFeatured: true,
      isPromoted: true,
    },
    {
      name: 'Forest Green Ribbed Mock-Neck Top',
      slug: 'forest-green-ribbed-mock-neck-top',
      description: 'Chic fitted mock neck in deep forest green ribbed knit, offering effortless style from desk to dinner.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 85.00,
      discountPercent: 10,
      rating: 4.8,
      reviewCount: 36,
      stock: 20,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Green',
        HexColor: '#065F46',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: 'Fine Viscose Rib Knit',
        Fit: 'Fitted Mock Neck',
        'Care Instructions': 'Machine wash cold gentle',
      }),
      tags: JSON.stringify(['women', 'top', 'green', 'forest', 'mock-neck', 'knit']),
    },
    {
      name: 'Sage Linen Casual Summer Top',
      slug: 'sage-linen-casual-summer-top',
      description: 'Earthy sage green sleeveless top in breezy organic linen with a subtle boatneck and clean stitched hem.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 75.00,
      discountPercent: 0,
      rating: 4.6,
      reviewCount: 25,
      stock: 23,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Green',
        HexColor: '#84CC16',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L, XL',
        Material: '100% Organic Washed Linen',
        Fit: 'Relaxed A-Line Fit',
        'Care Instructions': 'Machine wash cold, tumble dry low',
      }),
      tags: JSON.stringify(['women', 'top', 'green', 'sage', 'linen', 'summer']),
    },
    {
      name: 'Olive Tailored Satin Blouse',
      slug: 'olive-tailored-satin-blouse',
      description: 'Sophisticated olive green heavy satin with a spread collar, button placket, and elongated tailored cuffs.',
      categoryId: catWomensTops.id,
      brand: 'Maison Luxe',
      price: 140.00,
      discountPercent: 15,
      rating: 4.8,
      reviewCount: 30,
      stock: 15,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Green',
        HexColor: '#4D7C0F',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'S, M, L, XL',
        Material: 'Silk Satin Blend',
        Fit: 'Tailored Structured Fit',
        'Care Instructions': 'Dry clean only',
      }),
      tags: JSON.stringify(['women', 'top', 'green', 'olive', 'satin', 'tailored']),
    },
    {
      name: 'Mint Green Puff-Sleeve Top',
      slug: 'mint-green-puff-sleeve-top',
      description: 'Refreshing pastel mint green top with romantic puff sleeves, sweetheart neckline, and smocked back.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 90.00,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 22,
      stock: 18,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Green',
        HexColor: '#6EE7B7',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: '100% Poplin Cotton',
        Fit: 'Fitted Bodice, Puff Sleeves',
        'Care Instructions': 'Machine wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'green', 'mint', 'puff-sleeve', 'sweetheart']),
    },
    {
      name: 'Jade Peplum Georgette Blouse',
      slug: 'jade-peplum-georgette-blouse',
      description: 'Vibrant jade green sheer georgette with tonal camisole lining and an empire waist flared peplum.',
      categoryId: catWomensTops.id,
      brand: 'Maison Luxe',
      price: 110.00,
      discountPercent: 0,
      rating: 4.6,
      reviewCount: 19,
      stock: 13,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Green',
        HexColor: '#047857',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'S, M, L, XL',
        Material: 'Georgette Chiffon',
        Fit: 'Empire Peplum Fit',
        'Care Instructions': 'Hand wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'green', 'jade', 'peplum', 'georgette']),
    },
    {
      name: 'Pine Green Cashmere Long Sleeve Top',
      slug: 'pine-green-cashmere-long-sleeve-top',
      description: 'Ultra-luxurious pine green featherweight pure cashmere with a rolled boatneck collar and ribbed trim.',
      categoryId: catWomensTops.id,
      brand: 'Maison Luxe',
      price: 225.00,
      discountPercent: 10,
      rating: 5.0,
      reviewCount: 38,
      stock: 11,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Green',
        HexColor: '#14532D',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: '100% Grade-A Mongolian Cashmere',
        Fit: 'Tailored Knit Fit',
        'Care Instructions': 'Hand wash cold with wool detergent or dry clean',
      }),
      tags: JSON.stringify(['women', 'top', 'green', 'pine', 'cashmere', 'luxury']),
      isFeatured: true,
    },
    {
      name: 'Moss Green Wrap Kimono Top',
      slug: 'moss-green-wrap-kimono-top',
      description: 'Japanese-inspired kimono wrap top in textured moss green crepe with wide sleeves and a self-tie sash.',
      categoryId: catWomensTops.id,
      brand: 'Aura Atelier',
      price: 118.00,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 21,
      stock: 15,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Green',
        HexColor: '#365314',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'S, M, L, XL',
        Material: 'Viscose Blend Crepe',
        Fit: 'Relaxed Kimono Wrap',
        'Care Instructions': 'Hand wash cold',
      }),
      tags: JSON.stringify(['women', 'top', 'green', 'moss', 'kimono', 'wrap']),
    },
    {
      name: 'Pistachio Buttoned Ribbed Cardigan Top',
      slug: 'pistachio-buttoned-ribbed-cardigan-top',
      description: 'Pastel pistachio green fine-gauge knit designed to be worn solo as a fitted top with tortoiseshell buttons.',
      categoryId: catWomensTops.id,
      brand: 'Vogue Minimal',
      price: 80.00,
      discountPercent: 0,
      rating: 4.6,
      reviewCount: 24,
      stock: 19,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Green',
        HexColor: '#A7F3D0',
        Department: 'Women',
        Category: 'Tops',
        'Available Sizes': 'XS, S, M, L',
        Material: 'Organic Cotton & Silk Knit',
        Fit: 'Slim Ribbed Cardigan Fit',
        'Care Instructions': 'Machine wash cold delicate',
      }),
      tags: JSON.stringify(['women', 'top', 'green', 'pistachio', 'ribbed', 'cardigan']),
    },

    // =========================================================================
    // MALE T-SHIRTS — 5 BLACK T-SHIRTS
    // =========================================================================
    {
      name: 'Obsidian Luxe Pima Cotton Crewneck',
      slug: 'obsidian-luxe-pima-cotton-crewneck',
      description: 'Long-staple Peruvian Pima cotton crewneck in jet obsidian black. Ultra-soft feel with zero pilling.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 65.00,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 65,
      stock: 28,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
        'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Black',
        HexColor: '#000000',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL, XXL',
        Material: '100% Long-Staple Peruvian Pima Cotton',
        Fit: 'Modern Tailored Fit',
        'Care Instructions': 'Machine wash warm with dark colors, tumble dry low',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'black', 'pima-cotton', 'crewneck', 'luxury-basic']),
      isFeatured: true,
      isPromoted: true,
    },
    {
      name: 'Charcoal Heavyweight Boxy T-Shirt',
      slug: 'charcoal-heavyweight-boxy-t-shirt',
      description: 'Vintage-inspired 280 GSM heavyweight cotton tee with relaxed drop shoulders and durable ribbed collar.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 55.00,
      discountPercent: 10,
      rating: 4.8,
      reviewCount: 42,
      stock: 22,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Black',
        HexColor: '#1F2937',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL',
        Material: '100% 280 GSM Heavyweight Organic Cotton',
        Fit: 'Boxy Oversized Fit',
        'Care Instructions': 'Machine wash cold, hang dry recommended',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'black', 'charcoal', 'heavyweight', 'streetwear']),
    },
    {
      name: 'Jet Black Mercerized Cotton Slim Tee',
      slug: 'jet-black-mercerized-cotton-slim-tee',
      description: 'Mercerized cotton process provides deep color saturation and subtle formal sheen, perfect under blazers.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 75.00,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 37,
      stock: 19,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Black',
        HexColor: '#0A0A0A',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL',
        Material: '100% Double-Mercerized Giza Cotton',
        Fit: 'Slim Tailored Fit',
        'Care Instructions': 'Machine wash cold gentle, low iron',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'black', 'mercerized', 'formal', 'blazer-tee']),
    },
    {
      name: 'Onyx Minimalist Pocket T-Shirt',
      slug: 'onyx-minimalist-pocket-t-shirt',
      description: 'Clean pocket crewneck in deep onyx black combed cotton with seamless chest pocket and reinforced neckline.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 48.00,
      discountPercent: 0,
      rating: 4.6,
      reviewCount: 29,
      stock: 25,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Black',
        HexColor: '#111827',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL, XXL',
        Material: '100% Combed Cotton',
        Fit: 'Standard Regular Fit',
        'Care Instructions': 'Machine wash cold, tumble dry medium',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'black', 'pocket', 'casual', 'everyday']),
    },
    {
      name: 'Midnight Melange V-Neck T-Shirt',
      slug: 'midnight-melange-v-neck-t-shirt',
      description: 'Subtle charcoal-black heathered yarn with a tailored V-neck drop designed for sleek layering.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 58.00,
      discountPercent: 15,
      rating: 4.7,
      reviewCount: 31,
      stock: 20,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Black',
        HexColor: '#18181B',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'M, L, XL, XXL',
        Material: '95% Supima Cotton, 5% Elastane',
        Fit: 'Athletic Slim Fit',
        'Care Instructions': 'Machine wash cold with like colors',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'black', 'v-neck', 'melange', 'layering']),
    },

    // =========================================================================
    // MALE T-SHIRTS — 8 WHITE T-SHIRTS
    // =========================================================================
    {
      name: 'Classic Crisp White Supima Crewneck',
      slug: 'classic-crisp-white-supima-crewneck',
      description: 'The definitive luxury white tee: American-grown Supima cotton offering extraordinary softness and enduring brightness.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 60.00,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 88,
      stock: 35,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'White',
        HexColor: '#FFFFFF',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL, XXL',
        Material: '100% American Extra-Long Staple Supima Cotton',
        Fit: 'Tailored Classic Fit',
        'Care Instructions': 'Machine wash warm with whites, tumble dry medium',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'white', 'supima', 'crewneck', 'essential', 'bestseller']),
      isFeatured: true,
      isPromoted: true,
    },
    {
      name: 'Pure White Tailored Fit Cotton Tee',
      slug: 'pure-white-tailored-fit-cotton-tee',
      description: 'Sculpted shoulder seams and tapered sleeves create a clean athletic profile in pure optic white.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 52.00,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 45,
      stock: 26,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'White',
        HexColor: '#FAFAFA',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL',
        Material: '100% Ring-Spun Combed Cotton',
        Fit: 'Tailored Athletic Fit',
        'Care Instructions': 'Machine wash warm, tumble dry low',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'white', 'tailored', 'cotton', 'athletic']),
    },
    {
      name: 'Pearl White Organic Heavyweight Tee',
      slug: 'pearl-white-organic-heavyweight-tee',
      description: 'Heft and structure from 260 GSM organic cotton in a gentle warm pearl white tone with ribbed crew neck.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 55.00,
      discountPercent: 10,
      rating: 4.7,
      reviewCount: 39,
      stock: 22,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'White',
        HexColor: '#F4F4F5',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'M, L, XL, XXL',
        Material: '100% GOTS-Certified Organic Heavyweight Cotton',
        Fit: 'Relaxed Boxy Fit',
        'Care Instructions': 'Machine wash cold, line dry',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'white', 'organic', 'heavyweight', 'streetwear']),
    },
    {
      name: 'Alabaster Minimalist V-Neck Tee',
      slug: 'alabaster-minimalist-v-neck-tee',
      description: 'Clean shallow V-neck in alabaster white with micro-ribbing, tailored to sit perfectly under unbuttoned shirts.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 50.00,
      discountPercent: 0,
      rating: 4.6,
      reviewCount: 28,
      stock: 24,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'White',
        HexColor: '#F8FAFC',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL',
        Material: '95% Modal Cotton, 5% Spandex',
        Fit: 'Slim Fit',
        'Care Instructions': 'Machine wash cold gentle',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'white', 'v-neck', 'undershirt', 'minimalist']),
    },
    {
      name: 'Optical White Waffle Knit Crewneck',
      slug: 'optical-white-waffle-knit-crewneck',
      description: 'Textured thermal waffle knit in optical white with banded cuffs, delivering dimensional tactile interest.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 62.00,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 31,
      stock: 18,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'White',
        HexColor: '#FFFFFF',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL',
        Material: '100% Textured Cotton Waffle',
        Fit: 'Regular Fit',
        'Care Instructions': 'Machine wash cold, lay flat to dry',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'white', 'waffle-knit', 'thermal', 'textured']),
    },
    {
      name: 'Chalk White Relaxed Drop-Shoulder Tee',
      slug: 'chalk-white-relaxed-drop-shoulder-tee',
      description: 'Modern relaxed silhouette with drop shoulders and wider sleeves in soft chalk white brushed jersey.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 49.00,
      discountPercent: 15,
      rating: 4.5,
      reviewCount: 22,
      stock: 20,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'White',
        HexColor: '#F1F5F9',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'M, L, XL',
        Material: '100% Brushed Jersey Cotton',
        Fit: 'Relaxed Drop-Shoulder',
        'Care Instructions': 'Machine wash warm, tumble dry low',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'white', 'drop-shoulder', 'casual', 'oversized']),
    },
    {
      name: 'Ivory Ribbed Collar Essential T-Shirt',
      slug: 'ivory-ribbed-collar-essential-t-shirt',
      description: 'Slightly warm ivory white with an elevated 1-inch substantial ribbed collar that holds its shape wash after wash.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 54.00,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 36,
      stock: 25,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'White',
        HexColor: '#FFFBEB',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL, XXL',
        Material: '100% Combed Slub Cotton',
        Fit: 'Classic Regular Fit',
        'Care Instructions': 'Machine wash warm, tumble dry medium',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'white', 'ivory', 'ribbed-collar', 'classic']),
    },
    {
      name: 'Snow White Performance Moisture-Wicking Tee',
      slug: 'snow-white-performance-moisture-wicking-tee',
      description: 'Engineered poly-cotton performance blend in bright snow white with anti-odor silver ion technology.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 58.00,
      discountPercent: 0,
      rating: 4.6,
      reviewCount: 27,
      stock: 21,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'White',
        HexColor: '#FFFFFF',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL, XXL',
        Material: '60% Supima Cotton, 40% Performance Poly',
        Fit: 'Active Athletic Fit',
        'Care Instructions': 'Machine wash cold, tumble dry low, do not use softener',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'white', 'performance', 'active', 'moisture-wicking']),
    },

    // =========================================================================
    // MALE T-SHIRTS — 10 BLUE T-SHIRTS
    // =========================================================================
    {
      name: 'Deep Navy Mercerized Cotton Crewneck',
      slug: 'deep-navy-mercerized-cotton-crewneck',
      description: 'Lustrous deep midnight navy tee treated with double-mercerization for silk-like drape and rich color hold.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 72.00,
      discountPercent: 10,
      rating: 4.9,
      reviewCount: 52,
      stock: 27,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#1E3A8A',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL, XXL',
        Material: '100% Double-Mercerized Pima Cotton',
        Fit: 'Tailored Fit',
        'Care Instructions': 'Machine wash cold, low iron',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'navy', 'mercerized', 'formal']),
      isFeatured: true,
      isPromoted: true,
    },
    {
      name: 'Indigo Classic Fit Combed Cotton Tee',
      slug: 'indigo-classic-fit-combed-cotton-tee',
      description: 'Rope-dyed indigo yarn that develops unique faded patina with wear, cut in a timeless straight fit.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 56.00,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 38,
      stock: 23,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#1E40AF',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL',
        Material: '100% Indigo-Dyed Combed Cotton',
        Fit: 'Classic Regular Fit',
        'Care Instructions': 'Wash inside out in cold water, wash separately initially',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'indigo', 'vintage', 'raw']),
    },
    {
      name: 'Heather Slate Blue Minimalist Tee',
      slug: 'heather-slate-blue-minimalist-tee',
      description: 'Muted slate blue melange jersey offering understated color depth and exceptionally soft hand-feel.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 52.00,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 29,
      stock: 25,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#475569',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL',
        Material: '90% Supima Cotton, 10% Heather Poly',
        Fit: 'Modern Slim Fit',
        'Care Instructions': 'Machine wash warm, tumble dry low',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'slate', 'heather', 'minimalist']),
    },
    {
      name: 'Royal Blue Premium Slub Cotton T-Shirt',
      slug: 'royal-blue-premium-slub-cotton-t-shirt',
      description: 'Vibrant royal blue featuring organic yarn slubbing for textured dimension and warm-weather breathability.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 50.00,
      discountPercent: 15,
      rating: 4.6,
      reviewCount: 33,
      stock: 19,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#2563EB',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL, XXL',
        Material: '100% Organic Slub Jersey Cotton',
        Fit: 'Regular Fit',
        'Care Instructions': 'Machine wash cold, tumble dry medium',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'royal-blue', 'slub', 'summer']),
    },
    {
      name: 'Steel Blue Vintage Wash Pocket Tee',
      slug: 'steel-blue-vintage-wash-pocket-tee',
      description: 'Garment-dyed steel blue with subtle washed edges and a tailored chest pocket for relaxed weekend style.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 48.00,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 31,
      stock: 21,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#3B82F6',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'M, L, XL',
        Material: '100% Pigment-Dyed Cotton',
        Fit: 'Relaxed Fit',
        'Care Instructions': 'Machine wash cold with like colors',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'steel-blue', 'pocket', 'vintage-wash']),
    },
    {
      name: 'Cobalt Athletic Performance T-Shirt',
      slug: 'cobalt-athletic-performance-t-shirt',
      description: 'High-visibility cobalt blue with 4-way stretch, flatlock seams, and laser-perforated breathability zones.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 64.00,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 26,
      stock: 17,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#1D4ED8',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL, XXL',
        Material: '85% Micro-Poly, 15% Spandex Stretch',
        Fit: 'Athletic Fitted',
        'Care Instructions': 'Machine wash cold, do not bleach',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'cobalt', 'performance', 'stretch']),
    },
    {
      name: 'Marine Blue Enzyme-Washed Crewneck',
      slug: 'marine-blue-enzyme-washed-crewneck',
      description: 'Eco-friendly enzyme wash renders this marine blue cotton tee buttery-soft with broken-in comfort on day one.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 54.00,
      discountPercent: 10,
      rating: 4.7,
      reviewCount: 35,
      stock: 24,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#0284C7',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL',
        Material: '100% Enzyme-Washed Ring-Spun Cotton',
        Fit: 'Standard Regular Fit',
        'Care Instructions': 'Machine wash cold, tumble dry low',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'marine', 'enzyme-wash', 'soft']),
    },
    {
      name: 'Denim Blue Textured Slub T-Shirt',
      slug: 'denim-blue-textured-slub-t-shirt',
      description: 'Chambray denim-inspired blue with irregular slub yarn weaving that complements dark trousers and chinos.',
      categoryId: catMensTshirts.id,
      brand: 'Iron & Thread',
      price: 52.00,
      discountPercent: 0,
      rating: 4.5,
      reviewCount: 19,
      stock: 18,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#38BDF8',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'M, L, XL',
        Material: '100% Textured Slub Jersey',
        Fit: 'Regular Fit',
        'Care Instructions': 'Machine wash cold',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'denim-blue', 'slub', 'textured']),
    },
    {
      name: 'Cerulean Fine Gauge Knit Tee',
      slug: 'cerulean-fine-gauge-knit-tee',
      description: 'Luxe fine-gauge 18-gauge knit in bright cerulean blue with ribbed hem and cuffs for refined smart-casual dressing.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 85.00,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 30,
      stock: 15,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#0EA5E9',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL',
        Material: '100% Sea Island Cotton Knit',
        Fit: 'Tailored Knitwear Fit',
        'Care Instructions': 'Hand wash cold or dry clean',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'cerulean', 'knit', 'smart-casual']),
    },
    {
      name: 'Aegean Blue Lightweight Linen Blend Tee',
      slug: 'aegean-blue-lightweight-linen-blend-tee',
      description: 'Breathable Mediterranean aegean blue linen-cotton jersey designed for peak summer heat and effortless comfort.',
      categoryId: catMensTshirts.id,
      brand: 'Atelier Sartorial',
      price: 68.00,
      discountPercent: 12,
      rating: 4.6,
      reviewCount: 22,
      stock: 20,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#0369A1',
        Department: 'Men',
        Category: 'T-Shirts',
        'Available Sizes': 'S, M, L, XL, XXL',
        Material: '55% Linen, 45% Organic Cotton',
        Fit: 'Breezy Relaxed Fit',
        'Care Instructions': 'Machine wash cold, line dry',
      }),
      tags: JSON.stringify(['men', 't-shirt', 'blue', 'aegean', 'linen', 'resortwear']),
    },

    // =========================================================================
    // FEMALE JEANS — 3 ITEMS
    // =========================================================================
    {
      name: 'High-Rise Classic Straight Leg Indigo Denim',
      slug: 'high-rise-classic-straight-leg-indigo-denim',
      description: 'Vintage-inspired 11-inch high-rise with a flattering straight leg, 1% comfort stretch, and authentic indigo wash.',
      categoryId: catWomensJeans.id,
      brand: 'Denim Atelier',
      price: 165.00,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 74,
      stock: 22,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
        'https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Indigo',
        HexColor: '#1E3A8A',
        Department: 'Women',
        Category: 'Jeans',
        'Available Sizes': '25, 26, 27, 28, 29, 30, 31, 32',
        Material: '99% Organic Cotton, 1% Elastane',
        Fit: 'High-Rise Straight Leg',
        'Inseam Length': '30 inches',
        'Care Instructions': 'Machine wash cold inside out, hang dry',
      }),
      tags: JSON.stringify(['women', 'jeans', 'indigo', 'high-rise', 'straight-leg', 'denim', 'bestseller']),
      isFeatured: true,
      isPromoted: true,
    },
    {
      name: 'Ankle-Crop Slim Fit Vintage Blue Jeans',
      slug: 'ankle-crop-slim-fit-vintage-blue-jeans',
      description: 'Mid-rise slim silhouette with clean raw-edge ankle hems and hand-sanded vintage wash highlights.',
      categoryId: catWomensJeans.id,
      brand: 'Denim Atelier',
      price: 150.00,
      discountPercent: 10,
      rating: 4.8,
      reviewCount: 56,
      stock: 18,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#2563EB',
        Department: 'Women',
        Category: 'Jeans',
        'Available Sizes': '26, 27, 28, 29, 30, 31',
        Material: '98% Cotton, 2% Polyurethane Flex Stretch',
        Fit: 'Mid-Rise Slim Ankle Crop',
        'Inseam Length': '27 inches',
        'Care Instructions': 'Machine wash cold inside out, line dry',
      }),
      tags: JSON.stringify(['women', 'jeans', 'blue', 'ankle-crop', 'slim', 'vintage']),
    },
    {
      name: 'Wide-Leg Tailored Noir Black Denim Trousers',
      slug: 'wide-leg-tailored-noir-black-denim-trousers',
      description: 'Architectural high-rise wide-leg trousers in stay-black premium denim with front pressed creases.',
      categoryId: catWomensJeans.id,
      brand: 'Maison Luxe',
      price: 180.00,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 48,
      stock: 15,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Black',
        HexColor: '#111827',
        Department: 'Women',
        Category: 'Jeans',
        'Available Sizes': '26, 27, 28, 29, 30, 32',
        Material: '100% Rigid Turkish Cotton Denim',
        Fit: 'Ultra High-Rise Wide-Leg',
        'Inseam Length': '32 inches',
        'Care Instructions': 'Machine wash cold dark, hang dry',
      }),
      tags: JSON.stringify(['women', 'jeans', 'black', 'wide-leg', 'tailored', 'formal-denim']),
      isFeatured: true,
    },

    // =========================================================================
    // MALE JEANS — 5 ITEMS
    // =========================================================================
    {
      name: 'Straight Fit Raw Selvedge Denim Jeans',
      slug: 'straight-fit-raw-selvedge-denim-jeans',
      description: '14.5 oz Japanese shuttle-loom selvedge denim in unwashed deep indigo. Features red selvedge ID seam and copper rivets.',
      categoryId: catMensJeans.id,
      brand: 'Iron & Thread',
      price: 195.00,
      discountPercent: 0,
      rating: 5.0,
      reviewCount: 68,
      stock: 20,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Indigo',
        HexColor: '#1E3A8A',
        Department: 'Men',
        Category: 'Jeans',
        'Available Sizes': '29, 30, 31, 32, 33, 34, 36',
        Material: '100% 14.5oz Japanese Selvedge Cotton',
        Fit: 'Classic Straight Fit',
        'Inseam Length': '32 inches',
        'Care Instructions': 'Wear 6 months before first cold soak, hang dry',
      }),
      tags: JSON.stringify(['men', 'jeans', 'indigo', 'selvedge', 'raw-denim', 'heritage', 'bestseller']),
      isFeatured: true,
      isPromoted: true,
    },
    {
      name: 'Slim Tapered Stonewash Blue Jeans',
      slug: 'slim-tapered-stonewash-blue-jeans',
      description: 'Artfully distressed medium stonewash with a roomy top block that gently tapers toward a narrow leg opening.',
      categoryId: catMensJeans.id,
      brand: 'Denim Atelier',
      price: 145.00,
      discountPercent: 10,
      rating: 4.8,
      reviewCount: 47,
      stock: 24,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#3B82F6',
        Department: 'Men',
        Category: 'Jeans',
        'Available Sizes': '30, 31, 32, 33, 34',
        Material: '98% Cotton, 2% Spandex',
        Fit: 'Slim Tapered Fit',
        'Inseam Length': '32 inches',
        'Care Instructions': 'Machine wash cold, tumble dry low',
      }),
      tags: JSON.stringify(['men', 'jeans', 'blue', 'stonewash', 'slim-tapered', 'casual']),
    },
    {
      name: 'Classic Regular Fit Dark Indigo Jeans',
      slug: 'classic-regular-fit-dark-indigo-jeans',
      description: 'Timeless mid-rise 5-pocket jeans in clean dark indigo wash, crafted with just enough stretch for all-day comfort.',
      categoryId: catMensJeans.id,
      brand: 'Atelier Sartorial',
      price: 135.00,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 55,
      stock: 30,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Indigo',
        HexColor: '#172554',
        Department: 'Men',
        Category: 'Jeans',
        'Available Sizes': '30, 31, 32, 33, 34, 36',
        Material: '99% Organic Cotton, 1% Lycra',
        Fit: 'Classic Regular Fit',
        'Inseam Length': '32 inches',
        'Care Instructions': 'Machine wash cold inside out',
      }),
      tags: JSON.stringify(['men', 'jeans', 'indigo', 'regular-fit', '5-pocket', 'classic']),
    },
    {
      name: 'Relaxed Fit Washed Black Denim Jeans',
      slug: 'relaxed-fit-washed-black-denim-jeans',
      description: 'Vintage 90s inspired relaxed fit in enzyme-faded washed black denim with antiqued silver hardware.',
      categoryId: catMensJeans.id,
      brand: 'Iron & Thread',
      price: 140.00,
      discountPercent: 15,
      rating: 4.8,
      reviewCount: 39,
      stock: 19,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Black',
        HexColor: '#27272A',
        Department: 'Men',
        Category: 'Jeans',
        'Available Sizes': '30, 32, 34, 36',
        Material: '100% Cotton 13oz Washed Denim',
        Fit: 'Relaxed Easy Fit',
        'Inseam Length': '31 inches',
        'Care Instructions': 'Machine wash cold, tumble dry medium',
      }),
      tags: JSON.stringify(['men', 'jeans', 'black', 'washed-black', 'relaxed', 'vintage']),
    },
    {
      name: 'Modern Athletic Fit Deep Ocean Denim',
      slug: 'modern-athletic-fit-deep-ocean-denim',
      description: 'Engineered for athletic builds: extra room through the seat and thighs with a tailored clean taper from knee to ankle.',
      categoryId: catMensJeans.id,
      brand: 'Atelier Sartorial',
      price: 155.00,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 44,
      stock: 21,
      images: JSON.stringify([
        'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&q=80',
      ]),
      specifications: JSON.stringify({
        Color: 'Blue',
        HexColor: '#1E40AF',
        Department: 'Men',
        Category: 'Jeans',
        'Available Sizes': '31, 32, 33, 34, 36',
        Material: '94% Cotton, 5% Poly, 1% Elastane 360-Stretch',
        Fit: 'Athletic Tapered Fit',
        'Inseam Length': '32 inches',
        'Care Instructions': 'Machine wash cold, hang dry',
      }),
      tags: JSON.stringify(['men', 'jeans', 'blue', 'athletic-fit', 'stretch', 'comfort']),
      isFeatured: true,
    },
  ];

  console.log(`Creating ${productsData.length} apparel products...`);
  for (const prod of productsData) {
    await prisma.product.create({ data: prod });
  }

  // 5. Create Apparel Demo Reviews
  const seededProducts = await prisma.product.findMany({ take: 6 });
  if (seededProducts.length > 0) {
    await prisma.review.createMany({
      data: [
        {
          productId: seededProducts[0].id,
          userId: demoUser.id,
          userName: 'Alex Rivera',
          rating: 5,
          comment: 'The drape and quality of this silk blouse is breathtaking. True to size and looks stunning in person.',
        },
        {
          productId: seededProducts[0].id,
          userId: sarahUser.id,
          userName: 'Sarah Jenkins',
          rating: 5,
          comment: 'Vibrant color and French seam finishing. Worth every penny for formal dinners and work events.',
        },
        {
          productId: seededProducts[1].id,
          userId: demoUser.id,
          userName: 'Alex Rivera',
          rating: 5,
          comment: 'Impeccable cut and fabric weight. The peplum shape gives a flattering silhouette.',
        },
      ],
    });
  }

  // 6. Create Coupons
  await prisma.coupon.createMany({
    data: [
      {
        code: 'WELCOME10',
        discountPercent: 10,
        maxDiscount: 50,
        minSpend: 50,
        isActive: true,
      },
      {
        code: 'SAVE20',
        discountPercent: 20,
        maxDiscount: 100,
        minSpend: 150,
        isActive: true,
      },
      {
        code: 'ATELIER30',
        discountPercent: 30,
        maxDiscount: 150,
        minSpend: 250,
        isActive: true,
      },
      {
        code: 'FREESHIP',
        discountPercent: 5,
        maxDiscount: 20,
        minSpend: 40,
        isActive: true,
      },
    ],
  });

  console.log('Seeding completed successfully!');
  console.log(`- Categories: 4`);
  console.log(`- Total Apparel Products: ${productsData.length}`);
  console.log(`  * Female Tops: 31 (10 Red, 12 Blue, 9 Green)`);
  console.log(`  * Male T-Shirts: 23 (5 Black, 8 White, 10 Blue)`);
  console.log(`  * Jeans: 8 (3 Female, 5 Male)`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
